name = "cloud-notepad"
main = "src/index.js"
compatibility_date = "2022-05-13"

kv_namespaces = [
  { binding = "NOTES", id = "26cb564b215c4f17819d8524862eb2ae" },
  { binding = "SHARE", id = "5f38a28388f54e1a806bcd041bf9435c" }
]